version: '3'

services:
  server:
    container_name: app
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./src/:/app/server/src
    depends_on:
      - mysql

  mysql:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - /var/lib/mysql

  client:
    container_name: client
    build: ../client
    ports:
      - 3000:3000
    volumes:
      - ../client/src/:/app/client/src
    depends_on:
      - server

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
