version: '3'

services:
  server:
    image: loicbdev/wcs-student-project-back:latest
    command: sh -c "npm run build"
    expose:
      - 5000
    env_file:
      - ./.env.staging
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
  client:
    image: loicbdev/wcs-student-project-front:latest
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jura
    volumes:
      - /var/lib/mysql
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT:-8001}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
